### ISSUE TITLE
Polyfill should be updated to latest version

### ISSUE THREAD

**Issue by zhuowei** [CraneStation/wasi.dev#1]
There's been many changes to the WASI sandbox and the polyfill in the wasmtime repository since wasi.dev was initially created: it would be great if those changes can be added to the polyfill on wasi.dev.

Also, is there a CI process to automatically deploy newer versions of the polyfill to the website?

@sunfishcode

**Comment by sunfishcode** [comment]
I've now updated the polyfill manually. There's not currently a CI process to deploy newer versions automatically.

**Comment by zhuowei** [comment]
@sunfishcode Thanks!

**Comment by joel-porquet** [comment]
Sorry to reopen this, but I'm having a hard time understanding how the polyfill is built. Which pieces are you manually concatenating, and from where?
Thanks!

**Comment by sunfishcode** [comment]
The source is in [Wasmtime](https://github.com/CraneStation/wasmtime/) in the [wasmtime-wasi-c](https://github.com/CraneStation/wasmtime/tree/master/wasmtime-wasi-c/) crate.

js-polyfill/build.sh is a script to build it, and in theory it should still work, though in practice a few things have moved around so it's possible it needs updating, so feel free to post issues in the Wasmtime repo if things aren't working.

That should work, though it isn't currently being actively developed right now; our plan is to replace it with this: https://github.com/CraneStation/wasi-common/issues/19.

**Comment by sunfishcode** [comment]
You may also find https://github.com/WebAssembly/waterfall/blob/master/src/wasi.js useful. It's less feature-complete, but hand-written JS may be easier to work with, depending on your needs.

**Comment by joel-porquet** [comment]
Thanks, really appreciate your help!
